### ISSUE TITLE
[BUG] Refresh animation hidden behind "Contribute" button

### ISSUE THREAD

**Issue by RsTaK** [devstrons/heloworld#69]
### Description of the bug

Refresh animation hidden behind "Contribute" button when loading the page

### Steps to reproduce

- Press F5 (Reload the page)

### Expected behavior

Refresh animation should be removed or given a separate block in the page

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/37415061/134403959-5b4beb98-df14-466d-9d84-a7155310cfad.png)

### Desktop (please complete the information in the place holder)

_

### Smartphone (please complete the information in the place holder)

_

**Comment by krishguptadev** [comment]
How about aligning this on the bottom or making it a element of the navigation itself? 🤔

**Comment by aminoxix** [comment]
I think we've already done with the changes here:

![image](https://user-images.githubusercontent.com/75872316/195690535-1cd60440-216f-4f58-811d-6bc5fda49073.png)

Thanks guys for showing your interest, appreciate!
